### PR TITLE
Show login information on app pages

### PR DESCRIPTION
**Pull request by ajskateboarder**
IDK exactly how to describe but now whenever you login, a cookie is set containing the session ID (expires in 30 days)

When you go to a page it will check if the token cookie is there and make sure the token matches with a username in the DB

Screenshot 2023-08-02 062859

Also removed some redundant parts from `loggedin.html` so now it only shows news and stuff, not placeholder projects

### CODE REVIEW

**Comment by EngineerRunner** [comment]
it just threw an error when i tested it:

> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2213, in __call__
>     return self.wsgi_app(environ, start_response)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
>     response = self.handle_exception(e)
>                ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>          ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\Downloads\Snazzle-main(4)\Snazzle-main\app.py", line 127, in index
>     return stream_template(
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 205, in stream_template
>     return _stream(app, template, context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 169, in _stream
>     app.update_template_context(context)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 737, in update_template_context
>     context.update(func())
>                    ^^^^^^^
>   File "C:\Users\user\Downloads\Snazzle-main(4)\Snazzle-main\app.py", line 110, in context
>     username=username or user_data["user_name"],
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnboundLocalError: cannot access local variable 'username' where it is not associated with a value
> 127.0.0.1 - - [02/Aug/2023 14:40:18] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [02/Aug/2023 14:40:18] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [02/Aug/2023 14:40:18] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [02/Aug/2023 14:40:34] "GET / HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2213, in __call__
>     return self.wsgi_app(environ, start_response)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
>     response = self.handle_exception(e)
>                ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>          ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\Downloads\Snazzle-main(4)\Snazzle-main\app.py", line 127, in index
>     return stream_template(
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 205, in stream_template
>     return _stream(app, template, context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 169, in _stream
>     app.update_template_context(context)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 737, in update_template_context
>     context.update(func())
>                    ^^^^^^^
>   File "C:\Users\user\Downloads\Snazzle-main(4)\Snazzle-main\app.py", line 110, in context
>     username=username or user_data["user_name"],
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnboundLocalError: cannot access local variable 'username' where it is not associated with a value

**Comment by ajskateboarder** [comment]
Rookie mistake :P
Should be fixed now

**Comment by ajskateboarder** [comment]
Fixed again, lol

**Comment by redstone-dev** [comment]
Is this ready to merge?

**Comment by ajskateboarder** [comment]
this should work

**Pull request merged**
